### ISSUE TITLE
Create a Save button

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/Hawkeye#21]
Add a save button that persists the scheduled campaigns to mongo.

**Comment by sbsmith86** [comment]
Save button is there, still need to hook it up to the backend to actually persist the saved campaigns.

**Comment by mikefantini** [comment]
@sbsmith86 i think we can close this out actually. i don't think it needs to persist for the prototype. i just wanted to make sure we had it in the interface and that it made sense to users

thoughts on closing this guy out?

**Comment by sbsmith86** [comment]
I'm fine with closing it out for the prototype, let's just remember that this work needs to be done if/when we move forward.
